name: creusot
base: core24
version: '0.1'
summary: Snap for the Creusot formal verifier
description: |
  Formally verify Rust code with Creusot.

grade: stable
confinement: classic

apps:
  cargo-creusot:
    command: bin/cargo-creusot
    aliases:
      - cargo-creusot
    environment:
      PATH: $SNAP/share/creusot/bin:$SNAP/bin:$PATH
      XDG_DATA_HOME: $SNAP/share
      CREUSOT_DATA_HOME: $SNAP/share/creusot
      WHY3LIB: $SNAP/opam/5.3.0/lib/why3
      WHY3DATA: $SNAP/opam/5.3.0/share/why3
      WHY3CONFIG: $SNAP/share/creusot/why3.conf

parts:
  z3:
    plugin: nil
    build-packages:
      - curl
      - unzip
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/share/creusot/bin
      curl -L "https://github.com/Z3Prover/z3/releases/download/z3-4.15.3/z3-4.15.3-x64-glibc-2.39.zip" -o z3.zip
      unzip z3.zip -d z3_ext
      cp z3_ext/*/bin/z3 $CRAFT_PART_INSTALL/share/creusot/bin/

      rm -f z3.zip

  cvc5:
    plugin: nil
    build-packages:
      - curl
      - unzip
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/share/creusot/bin
      curl -L "https://github.com/cvc5/cvc5/releases/download/cvc5-1.3.1/cvc5-Linux-x86_64-static-gpl.zip" -o cvc5.zip
      unzip cvc5.zip -d cvc5_ext
      cp cvc5_ext/*/bin/cvc5 $CRAFT_PART_INSTALL/share/creusot/bin/

      rm -f cvc5.zip

  cvc4:
    plugin: nil
    build-packages:
      - curl
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/share/creusot/bin
      curl -L "https://github.com/CVC4/CVC4-archived/releases/download/1.8/cvc4-1.8-x86_64-linux-opt" -o $CRAFT_PART_INSTALL/share/creusot/bin/cvc4
      chmod +x $CRAFT_PART_INSTALL/share/creusot/bin/cvc4

  altergo:
    plugin: nil
    build-packages:
      - curl
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/share/creusot/bin
      curl -L "https://github.com/OCamlPro/alt-ergo/releases/download/v2.6.2/alt-ergo-v2.6.2-x86_64-linux-musl" -o $CRAFT_PART_INSTALL/share/creusot/bin/alt-ergo
      chmod +x $CRAFT_PART_INSTALL/share/creusot/bin/alt-ergo

  opam:
    plugin: nil
    build-packages:
      - curl
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/bin
      export OPAMROOT=$CRAFT_PART_INSTALL/opam
      export OPAM_DISABLE_SANDBOXING=1
      export OPAMROOTISOK=1
      export OPAMYES=1

      export OPAMCONFIRMLEVEL=unsafe-yes
      export DEBIAN_FRONTEND=noninteractive

      curl -L "https://github.com/ocaml/opam/releases/download/2.2.1/opam-2.2.1-x86_64-linux" -o /usr/local/bin/opam
      chmod +x /usr/local/bin/opam
  
  creusot:
    after: [opam]
    plugin: rust
    source: https://github.com/creusot-rs/creusot.git
    source-type: git
    source-commit: a0ae3291a8a10bdb4c09a259e8415f6e1e2465fe
    build-packages:
      - make
      - gcc
      - m4
      - pkg-config
      - libgmp-dev
      - patch
    override-build: |

      mkdir -p $CRAFT_PART_INSTALL/bin

      export BUILD_DIR=/snap/creusot/current
      mkdir -p $BUILD_DIR

      export OPAMROOT=$BUILD_DIR/opam
      export OPAM_DISABLE_SANDBOXING=1
      export OPAMROOTISOK=1
      export OPAMYES=1

      export OPAMCONFIRMLEVEL=unsafe-yes
      export DEBIAN_FRONTEND=noninteractive

      opam init default https://opam.ocaml.org --disable-sandboxing

      opam switch create 5.3.0
      
      eval $(opam env)

      opam install . --deps-only --confirm-level=unsafe-yes

      mkdir -p $BUILD_DIR/bin
      cp $OPAMROOT/5.3.0/bin/why3* $BUILD_DIR/bin/

      rustup default stable
      sed -i 's|env!("CARGO_MANIFEST_DIR")|"/snap/creusot/current/creusot/cargo-creusot"|g' cargo-creusot/src/new.rs
      craftctl default

      cp target/release/cargo-creusot $BUILD_DIR/bin/
      cp target/release/creusot-rustc $BUILD_DIR/bin/

      mkdir -p $BUILD_DIR/share/creusot/bin
      mkdir -p $BUILD_DIR/share/creusot/share/why3find/packages/creusot/creusot

      cargo run --bin prelude-generator
      cp target/creusot/packages/creusot/creusot/* $BUILD_DIR/share/creusot/share/why3find/packages/creusot/creusot/

      cp why3find.json $BUILD_DIR/share/creusot/why3find.json
      cp creusot-deps.opam $BUILD_DIR/share/creusot/creusot-deps.opam
      cp $OPAMROOT/5.3.0/bin/why3* $BUILD_DIR/share/creusot/bin/

      cp -r $CRAFT_PART_SRC $BUILD_DIR/creusot

      rm -rf target/

      rm -rf $OPAMROOT/download-cache
      rm -rf $OPAMROOT/repo/default/archives/*

      cp -r $BUILD_DIR/* $CRAFT_PART_INSTALL/


